# Exploración inicial del dataset

## Objetivo

En este notebook se realiza una primera exploración del dataset de alquileres de departamentos en CABA.

El objetivo es comprender la estructura de los datos, identificar las variables disponibles y detectar posibles problemas antes de comenzar la etapa de limpieza y transformación.

In [1]:
import numpy as np

In [2]:
import pandas as pd

df = pd.read_pickle("../data/raw/alquiler_departamentos_consolidado.pkl")

In [3]:
df.head()

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
0,54517317,USD 500,"Belgrano, Capital Federal",Blanco Encalada al 1401,"[58 m² tot., 1 amb., 1 baño]",Monoambiente con Jardin con Parrilla Privado y...,$ 235.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
1,54209811,USD 950,"Palermo Hollywood, Palermo",Convención al 1900,"[55 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Palermo departamento en alquiler totalmente eq...,$ 230.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
2,54139823,$ 470.000,"Núñez, Capital Federal",Av. Libertador y Manzanares 1600,"[38 m² tot., 1 amb., 1 baño]",Monoambiente en alquiler en nuñez. Excelente u...,$ 80.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
3,54339837,$ 320.000,"Caballito, Capital Federal",ARANGUREN 600. Entre Colpayo y Avenida pueyrredon,"[30 m² tot., 1 amb., 1 dorm.]",Alquiler de Departamento 1 ambiente en Caballi...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
4,54239549,USD 1.100,"Belgrano, Capital Federal",Virrey Loreto 2200,"[75 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Moderno Departamento 2 ambientes. Muy luminoso...,$ 200.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler

In [4]:
df.shape

(57343, 11)

In [5]:
df.columns

Index(['id', 'Price', 'Location', 'Address', 'Features', 'Description',
       'Expensas', 'Link', 'scrap_date', 'type_building', 'type_operation'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57343 entries, 0 to 57342
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              57343 non-null  object
 1   Price           57343 non-null  object
 2   Location        57343 non-null  object
 3   Address         57343 non-null  object
 4   Features        57343 non-null  object
 5   Description     57343 non-null  object
 6   Expensas        45375 non-null  object
 7   Link            57343 non-null  object
 8   scrap_date      57343 non-null  datetime64[us]
 9   type_building   57343 non-null  object
 10  type_operation  57343 non-null  object
dtypes: datetime64[us](1), object(10)
memory usage: 4.8+ MB

In [7]:
df.head(10)

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
0,54517317,USD 500,"Belgrano, Capital Federal",Blanco Encalada al 1401,"[58 m² tot., 1 amb., 1 baño]",Monoambiente con Jardin con Parrilla Privado y...,$ 235.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
1,54209811,USD 950,"Palermo Hollywood, Palermo",Convención al 1900,"[55 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Palermo departamento en alquiler totalmente eq...,$ 230.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
2,54139823,$ 470.000,"Núñez, Capital Federal",Av. Libertador y Manzanares 1600,"[38 m² tot., 1 amb., 1 baño]",Monoambiente en alquiler en nuñez. Excelente u...,$ 80.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
3,54339837,$ 320.000,"Caballito, Capital Federal",ARANGUREN 600. Entre Colpayo y Avenida pueyrredon,"[30 m² tot., 1 amb., 1 dorm.]",Alquiler de Departamento 1 ambiente en Caballi...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
4,54239549,USD 1.100,"Belgrano, Capital Federal",Virrey Loreto 2200,"[75 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Moderno Departamento 2 ambientes. Muy luminoso...,$ 200.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
5,54373994,$ 650.000,"Palermo, Capital Federal","SCALABRINI ORTIZ, RAUL, AV. 2700. Entre Beruti...","[70 m² tot., 4 amb., 3 dorm., 2 baños]","Departamento 4 ambientes en Palermo, Capital F...",$ 190.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
6,54437016,$ 900.000,"Palermo, Capital Federal",Mansilla 3700,"[65 m² tot., 3 amb., 2 dorm., 1 baño]",Ubicación: Apartamento de tres ambientes en un...,$ 83.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
7,54549118,$ 590.000,"Palermo, Capital Federal",Uriarte 2300,"[33 m² tot., 1 amb., 1 baño]",Corredor Responsable: Monica Alejandra Mazza c...,$ 121.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
8,52914698,USD 1.300,"Villa Crespo, Capital Federal",Costa Rica al 4300,"[66 m² tot., 3 amb., 2 dorm., 1 baño, 1 coch.]",Tres ambientes con balcón ubicado en costa ric...,$ 80.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
9,54449591,$ 450.000,"Colegiales, Capital Federal",Conde al 700,"[43 m² tot., 2 amb., 1 dorm., 1 baño]","Departamento 2 ambientes, excelente ubicaciónD...",$ 95.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler

In [8]:
df.isnull().sum()

id                    0
Price                 0
Location              0
Address               0
Features              0
Description           0
Expensas          11968
Link                  0
scrap_date            0
type_building         0
type_operation        0
dtype: int64

## Observaciones

- El dataset contiene 57.343 publicaciones.
- La columna `Expensas` presenta 11.968 valores faltantes.
- El resto de las columnas no presenta valores nulos.
- Será necesario analizar más adelante cómo tratar los valores faltantes de `Expensas`.

In [9]:
df["scrap_date"].nunique()

5

In [10]:
df["scrap_date"].sort_values().unique()

<DatetimeArray>
['2024-09-23 08:28:14.272951', '2024-09-24 12:26:30.907747',
 '2024-09-29 23:47:13.054893', '2025-03-09 00:26:57.589025',
 '2025-07-12 13:35:44.207335']
Length: 5, dtype: datetime64[us]

## Observaciones sobre la fecha de scraping

- El dataset contiene publicaciones obtenidas en 5 fechas distintas.
- Las fechas abarcan desde septiembre de 2024 hasta julio de 2025.
- Esto permitirá realizar análisis temporales una vez que los datos estén limpios.

In [11]:
df.describe(include="all")

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
count,57343,57343,57343,57343,57343,57343,45375,57343,57343,57343,57343
unique,31338,736,89,23235,4039,31655,2483,31748,NaN,1,1
top,54487465,$ 450.000,"Palermo, Capital Federal",Dirección no informada,"[40 m² tot., 2 amb., 1 dorm., 1 baño]",Edificio en torreSeguridad 24 hrsParque / Jard...,$ 100.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,NaN,departamentos,alquiler
freq,5,2613,6614,430,1576,31,1825,5,NaN,57343,57343
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-15 04:01:33.844427,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-23 08:28:14.272951,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-24 12:26:30.907747,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-29 23:47:13.054893,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-09 00:26:57.589025,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-12 13:35:44.207335,NaN,NaN

In [12]:
df["id"].value_counts().head(10)

id
54487465    5
53760505    5
52978480    5
44626608    5
48296864    5
45818662    5
54133703    5
52969886    5
54239592    5
53263870    5
Name: count, dtype: int64

In [13]:
df[df["id"] == "54487465"]

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
34,54487465,$ 380.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 65.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
14824,54487465,$ 380.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 65.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-24 12:26:30.907747,departamentos,alquiler
28126,54487465,$ 380.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 65.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-29 23:47:13.054893,departamentos,alquiler
42499,54487465,$ 400.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2025-03-09 00:26:57.589025,departamentos,alquiler
55587,54487465,$ 440.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2025-07-12 13:35:44.207335,departamentos,alquiler

## Observaciones sobre los identificadores (`id`)

- Los identificadores no representan registros únicos del dataset.
- Un mismo `id` puede aparecer en distintas fechas de scraping.
- Esto indica que el dataset conserva el historial de una misma publicación a lo largo del tiempo.
- Gracias a esta característica será posible realizar análisis de evolución de precios y expensas entre distintas fechas.

In [14]:
df["type_operation"].value_counts()

type_operation
alquiler    57343
Name: count, dtype: int64

In [15]:
df["type_building"].value_counts()

type_building
departamentos    57343
Name: count, dtype: int64

## Observaciones sobre variables constantes

- La columna `type_operation` contiene únicamente el valor `alquiler`.
- La columna `type_building` contiene únicamente el valor `departamentos`.
- Ambas columnas no aportan variabilidad al análisis y podrían eliminarse durante la etapa de limpieza de datos.

In [16]:
df["Location"].value_counts()

Location
Palermo, Capital Federal            6614
Recoleta, Capital Federal           6503
Belgrano, Capital Federal           4525
Puerto Madero, Capital Federal      3276
Barrio Norte, Capital Federal       2636
                                    ...
Belgrano C, Colegiales                 2
Botánico, Recoleta                     1
Villa Riachuelo, Capital Federal       1
Temperley, San Telmo                   1
Los Perales, Mataderos                 1
Name: count, Length: 89, dtype: int64

In [17]:
df_clean = df.copy()

In [18]:
df_clean["Price"].str.startswith("USD").value_counts()

Price
False    34221
True     23122
Name: count, dtype: int64

## Observaciones sobre la columna `Price`

La columna `Price` contiene información de dos variables: la moneda y el importe.

Se identificaron publicaciones en pesos argentinos (`$`) y en dólares estadounidenses (`USD`).

Aproximadamente el 60% de las publicaciones están expresadas en pesos y el 40% en dólares.

Será necesario separar la moneda del valor numérico para facilitar el análisis.

In [19]:
# Extrae la moneda de Price y la guarda en una nueva columna llamada "currecy"
df_clean["currency"] = df_clean["Price"].str.extract(r"(USD|\$)")[0]

In [20]:
# Comprueba cuantos registros hay en cada moneda
df_clean["currency"].value_counts()

currency
$      34069
USD    23122
Name: count, dtype: int64

## Limpieza de la columna `Price`

La columna `Price` contiene dos tipos de información:

- La moneda (`USD` o `$`).
- El valor del alquiler.

Se extrae el importe numérico y se almacena en una nueva columna llamada `price_value`, manteniendo la columna original `Price` para conservar el dato tal como fue obtenido.

In [21]:
# Elimina separadores y símbolos de moneda 
# para preparar el precio para convertirlo a número.
price_test = pd.to_numeric(
    df_clean["Price"]
    .str.replace(".", "", regex=False)
    .str.replace("USD", "", regex=False)
    .str.replace("$", "", regex=False),
    errors="coerce"
)

# Cuenta los valores que no pudieron convertirse a número
price_test.isna().sum()

np.int64(152)

In [22]:
# Identifica qué valores originales provocaron conversiones inválidas.
df_clean.loc[price_test.isna(), "Price"].value_counts()

Price
Consultar precio    152
Name: count, dtype: int64

In [23]:
# Guarda el precio numérico limpio en price_value.
df_clean["price_value"] = price_test

In [24]:
# Verifica visualmente la correspondencia entre 
# precio original y precio numérico.
df_clean[["Price", "price_value"]].head(10)

       Price  price_value
0    USD 500        500.0
1    USD 950        950.0
2  $ 470.000     470000.0
3  $ 320.000     320000.0
4  USD 1.100       1100.0
5  $ 650.000     650000.0
6  $ 900.000     900000.0
7  $ 590.000     590000.0
8  USD 1.300       1300.0
9  $ 450.000     450000.0

In [25]:
# Comprueba cuántos precios quedaron como valores faltantes.
df_clean["price_value"].isna().sum()

np.int64(152)

## Exploración de los valores de `price_value`

Una vez obtenido el valor numérico, se analiza su distribución para detectar valores atípicos o inconsistentes antes de continuar con la limpieza.

In [26]:
# Resume la distribución estadística de los precios.
df_clean["price_value"].describe()

count    5.719100e+04
mean     6.345038e+06
std      8.060599e+08
min      1.000000e+00
25%      1.200000e+03
50%      3.500000e+05
75%      5.000000e+05
max      1.111111e+11
Name: price_value, dtype: float64

In [27]:
# Muestra los precios más bajos para detectar valores sospechosos.
df_clean["price_value"].sort_values().head(20)

33243    1.0
48450    1.0
48467    1.0
38144    1.0
48833    1.0
9691     1.0
20438    1.0
9703     1.0
9681     1.0
26942    1.0
37482    1.0
9370     1.0
17452    1.0
22161    1.0
9732     1.0
38014    1.0
33048    1.0
12679    1.0
19969    1.0
20003    1.0
Name: price_value, dtype: float64

In [28]:
# Muestra los precios más altos para detectar valores extremos.
df_clean["price_value"].sort_values(ascending=False).head(20)

26963    1.111111e+11
40461    1.111111e+11
13650    1.111111e+11
31361    1.111111e+10
48296    1.111111e+07
15841    9.999999e+06
29494    9.999999e+06
1468     9.999999e+06
46892    9.999999e+06
16938    7.500000e+06
31349    7.500000e+06
31822    5.000000e+06
18821    5.000000e+06
55955    5.000000e+06
35022    4.850000e+06
20099    4.850000e+06
8747     4.850000e+06
45879    4.800000e+06
9955     4.500000e+06
23105    4.500000e+06
Name: price_value, dtype: float64

## Detección y tratamiento de valores extremos

Durante la exploración se detectaron valores que no parecen representar un alquiler mensual convencional.

Se establecieron inicialmente dos límites para investigar posibles errores:

- Valores menores o iguales a `1`.
- Valores mayores o iguales a `10.000.000`.

Estos valores se revisan antes de decidir si deben excluirse del análisis.

In [29]:
print("Precios <= 1:", (df_clean["price_value"] <= 1).sum())
print("Precios >= 10.000.000:", (df_clean["price_value"] >= 10_000_000).sum())

Precios <= 1: 35
Precios >= 10.000.000: 5

In [30]:
# Identifica registros con precios extremadamente altos.
df_clean.loc[
    df_clean["price_value"] >= 10_000_000,
    ["Price", "price_value"]
]

                   Price   price_value
13650  $ 111.111.111.111  1.111111e+11
26963  $ 111.111.111.111  1.111111e+11
31361   $ 11.111.111.111  1.111111e+10
40461  $ 111.111.111.111  1.111111e+11
48296       $ 11.111.111  1.111111e+07

In [31]:
# Cuenta cuántos registros presentan precios extremadamente altos.
(df_clean["price_value"] >= 10_000_000).sum()

np.int64(5)

In [32]:
# Identifica registros con precios iguales o inferiores a 1.
(df_clean["price_value"] <= 1).sum()

np.int64(35)

In [33]:
# Revisa los registros con precios extremadamente bajos.
df_clean.loc[
    df_clean["price_value"] <= 1,
    ["Price", "price_value"]
].head(20)

       Price  price_value
907    USD 1          1.0
5591   USD 1          1.0
8639   USD 1          1.0
9370   USD 1          1.0
9681   USD 1          1.0
9691   USD 1          1.0
9703     $ 1          1.0
9732     $ 1          1.0
12679    $ 1          1.0
14218  USD 1          1.0
17452    $ 1          1.0
19746    $ 1          1.0
19879  USD 1          1.0
19969  USD 1          1.0
20003    $ 1          1.0
20438  USD 1          1.0
22161  USD 1          1.0
22731  USD 1          1.0
26942    $ 1          1.0
33048  USD 1          1.0

In [34]:
# Muestra la frecuencia de cada valor extremadamente bajo.
df_clean.loc[
    df_clean["price_value"] <= 1,
    "price_value"
].value_counts()

price_value
1.0    35
Name: count, dtype: int64

## Revisión de precios elevados en dólares

Los precios expresados en USD requieren un análisis separado, ya que un valor elevado puede corresponder a una publicación incorrecta, a una modalidad de alquiler diferente o a información adicional incluida en la descripción.

Se revisan especialmente los registros con precios iguales o superiores a USD 10.000.

In [35]:
# Obtiene los alquileres en USD con valores 
# muy elevados para inspeccionarlos.
usd_altos = df_clean[
    (df_clean["currency"] == "USD") &
    (df_clean["price_value"] >= 10_000)
].copy()
print("Registros USD >= 10.000:", len(usd_altos))

Registros USD >= 10.000: 345

## Revisión de valores USD extremadamente altos

Se realiza una segunda revisión sobre precios iguales o superiores a USD 50.000 para determinar si corresponden realmente al alquiler mensual o si representan otra modalidad de publicación.

In [36]:
# Aísla los casos con precios USD extremadamente altos.
usd_muy_altos = df_clean.loc[
    (df_clean["currency"] == "USD") &
    (df_clean["price_value"] >= 50_000),
    ["id", "Price", "price_value", "Location", "Features", "Description"]
]

print("Registros USD >= 50.000:", len(usd_muy_altos))

print(
    usd_muy_altos[
        ["id", "Price", "price_value", "Location", "Features"]
    ].to_string()
)

Registros USD >= 50.000: 64
             id        Price  price_value                               Location                                        Features
1878   54281958  USD 140.000     140000.0                   Las Cañitas, Palermo           [52 m² tot., 3 amb., 2 dorm., 1 baño]
3736   54337464  USD 490.000     490000.0         Villa Urquiza, Capital Federal                    [36 m² tot., 1 amb., 1 baño]
4748   54349411  USD 450.000     450000.0              Belgrano, Capital Federal           [41 m² tot., 2 amb., 1 dorm., 1 baño]
5697   53211252  USD 700.000     700000.0         Villa Urquiza, Capital Federal          [74 m² tot., 2 amb., 1 dorm., 2 baños]
6178   54184761   USD 85.000      85000.0               Palermo, Capital Federal           [31 m² tot., 1 amb., 1 dorm., 1 baño]
6347   54295858  USD 450.000     450000.0              Recoleta, Capital Federal           [45 m² tot., 2 amb., 1 dorm., 1 baño]
7137   54469665  USD 650.000     650000.0              Belgrano, Capital Federal           [74 m² tot., 3 amb., 2 dorm., 1 baño]
10113  54516396  USD 550.000     550000.0              Recoleta, Capital Federal                    [40 m² tot., 1 amb., 1 baño]
11096  54528540  USD 135.000     135000.0              Floresta, Capital Federal          [105 m² tot., 3 amb., 2 dorm., 1 baño]
11716  54146232  USD 450.000     450000.0             Palermo Hollywood, Palermo                   [33 m² tot., 1 dorm., 1 baño]
12297  54333234  USD 250.000     250000.0             Balvanera, Capital Federal                    [17 m² tot., 1 amb., 1 baño]
12726  54269567  USD 400.000     400000.0                  Palermo Soho, Palermo           [35 m² tot., 2 amb., 1 dorm., 1 baño]
12898  54239689  USD 800.000     800000.0                 Núñez, Capital Federal  [64 m² tot., 3 amb., 2 dorm., 1 baño, 1 coch.]
16061  54281958  USD 140.000     140000.0                   Las Cañitas, Palermo           [52 m² tot., 3 amb., 2 dorm., 1 baño]
17615  54337464  USD 490.000     490000.0         Villa Urquiza, Capital Federal                    [36 m² tot., 1 amb., 1 baño]
19197  54564453  USD 450.000     450000.0              Belgrano, Capital Federal           [41 m² tot., 2 amb., 1 dorm., 1 baño]
19645  54566160  USD 600.000     600000.0               Palermo, Capital Federal           [58 m² tot., 2 amb., 1 dorm., 1 baño]
20702  54333234  USD 250.000     250000.0             Balvanera, Capital Federal                    [17 m² tot., 1 amb., 1 baño]
21723  54469665  USD 650.000     650000.0              Belgrano, Capital Federal           [74 m² tot., 3 amb., 2 dorm., 1 baño]
22649  54184761   USD 85.000      85000.0               Palermo, Capital Federal           [31 m² tot., 1 amb., 1 dorm., 1 baño]
23036  53211252  USD 700.000     700000.0         Villa Urquiza, Capital Federal          [74 m² tot., 2 amb., 1 dorm., 2 baños]
24173  54516396  USD 550.000     550000.0              Recoleta, Capital Federal                    [40 m² tot., 1 amb., 1 baño]
25174  54146232  USD 450.000     450000.0             Palermo Hollywood, Palermo                   [33 m² tot., 1 dorm., 1 baño]
26300  54295858  USD 420.000     420000.0              Recoleta, Capital Federal           [45 m² tot., 2 amb., 1 dorm., 1 baño]
26805  54568108  USD 400.000     400000.0             Caballito, Capital Federal           [47 m² tot., 2 amb., 1 dorm., 1 baño]
27382  54239689  USD 800.000     800000.0                 Núñez, Capital Federal  [64 m² tot., 3 amb., 2 dorm., 1 baño, 1 coch.]
27764  54269567  USD 400.000     400000.0                  Palermo Soho, Palermo           [35 m² tot., 2 amb., 1 dorm., 1 baño]
29907  54281958  USD 140.000     140000.0                   Las Cañitas, Palermo           [52 m² tot., 3 amb., 2 dorm., 1 baño]
30424  54601285   USD 67.800      67800.0              Belgrano, Capital Federal                    [22 m² tot., 1 amb., 1 baño]
31276  54337464  USD 490.000     490000.0         Villa Urquiza, Capital Federal                    [36 m² tot., 1 amb., 1 baño]
31757  54564453  USD 450.000     450000.0              Belgrano, Capital Federal           [41 m² tot., 2 amb., 1 dorm., 1 baño]
33133  54601118  USD 750.000     750000.0               Palermo, Capital Federal           [49 m² tot., 2 amb., 1 dorm., 1 baño]
34154  54333234  USD 250.000     250000.0             Balvanera, Capital Federal                    [17 m² tot., 1 amb., 1 baño]
34255  54146232  USD 450.000     450000.0             Palermo Hollywood, Palermo                   [33 m² tot., 1 dorm., 1 baño]
36467  54295858  USD 420.000     420000.0              Recoleta, Capital Federal           [45 m² tot., 2 amb., 1 dorm., 1 baño]
36801  54184761   USD 85.000      85000.0               Palermo, Capital Federal           [31 m² tot., 1 amb., 1 dorm., 1 baño]
37431  54572897  USD 172.000     172000.0              Belgrano, Capital Federal           [91 m² tot., 4 amb., 3 dorm., 1 baño]
39122  54516396  USD 550.000     550000.0              Recoleta, Capital Federal                    [40 m² tot., 1 amb., 1 baño]
40291  53211252  USD 700.000     700000.0         Villa Urquiza, Capital Federal          [74 m² tot., 2 amb., 1 dorm., 2 baños]
40674  54269567  USD 400.000     400000.0                  Palermo Soho, Palermo           [35 m² tot., 2 amb., 1 dorm., 1 baño]
41642  55604578  USD 650.000     650000.0               Palermo, Capital Federal           [55 m² tot., 2 amb., 1 dorm., 1 baño]
42275  55715414  USD 550.000     550000.0                 Núñez, Capital Federal           [35 m² tot., 2 amb., 1 dorm., 1 baño]
46670  55630817  USD 720.000     720000.0              Belgrano, Capital Federal           [47 m² tot., 2 amb., 1 dorm., 1 baño]
47924  54146232  USD 500.000     500000.0             Palermo Hollywood, Palermo                   [33 m² tot., 1 dorm., 1 baño]
48068  55542257  USD 800.000     800000.0          Barrio Norte, Capital Federal           [64 m² tot., 3 amb., 2 dorm., 1 baño]
48126  55541936  USD 750.000     750000.0          Barrio Norte, Capital Federal           [57 m² tot., 3 amb., 2 dorm., 1 baño]
48550  52803473  USD 119.600     119600.0                 Palermo Viejo, Palermo           [46 m² tot., 2 amb., 1 dorm., 1 baño]
49422  55469549   USD 65.000      65000.0  Centro / Microcentro, Capital Federal           [35 m² tot., 2 amb., 1 dorm., 1 baño]
51605  54101372  USD 450.000     450000.0               Almagro, Capital Federal                    [30 m² tot., 1 amb., 1 baño]
51880  55675852  USD 450.000     450000.0                 Boedo, Capital Federal                    [24 m² tot., 1 amb., 1 baño]
52331  55689839  USD 650.000     650000.0           San Nicolás, Capital Federal           [42 m² tot., 2 amb., 1 dorm., 1 baño]
52397  55714131  USD 950.000     950000.0                Flores, Capital Federal                      [5 amb., 4 dorm., 3 baños]
53121  55718038  USD 550.000     550000.0               Palermo, Capital Federal           [50 m² tot., 2 amb., 1 dorm., 1 baño]
53577  55715147  USD 550.000     550000.0           San Nicolás, Capital Federal           [50 m² tot., 2 amb., 1 dorm., 1 baño]
53581  55714930  USD 400.000     400000.0                Retiro, Capital Federal           [36 m² tot., 2 amb., 1 dorm., 1 baño]
53716  55721251  USD 800.000     800000.0              Recoleta, Capital Federal           [82 m² tot., 3 amb., 3 dorm., 1 baño]
53750  55720103  USD 750.000     750000.0             Caballito, Capital Federal           [40 m² tot., 2 amb., 1 dorm., 1 baño]
53758  55646489  USD 870.000     870000.0                 Núñez, Capital Federal           [64 m² tot., 2 amb., 1 dorm., 1 baño]
53941  55382363  USD 900.000     900000.0              Belgrano, Capital Federal         [100 m² tot., 4 amb., 3 dorm., 2 baños]
54714  55706975   USD 60.000      60000.0                  Palermo Soho, Palermo           [35 m² tot., 4 amb., 1 dorm., 1 baño]
55041  55722649  USD 750.000     750000.0          Barrio Norte, Capital Federal           [75 m² tot., 3 amb., 2 dorm., 1 baño]
56364  56655198  USD 410.000     410000.0          Villa Crespo, Capital Federal                    [35 m² tot., 1 amb., 1 baño]
56464  56675648  USD 550.000     550000.0               Palermo, Capital Federal                    [32 m² tot., 1 amb., 1 baño]
56519  56657604   USD 75.000      75000.0             Balvanera, Capital Federal                    [56 m² tot., 1 amb., 1 baño]

## Identificación de alquileres temporarios

Los alquileres temporarios pueden presentar precios expresados por día, semana, noche o estadía, por lo que sus valores no son directamente comparables con los alquileres mensuales.

Se crea una variable que permite identificarlos a partir de términos presentes en la descripción.

In [37]:
# Marca publicaciones que mencionan modalidades de alquiler temporario.
df_clean["es_temporario"] = df_clean["Description"].str.contains(
    r"alquiler temporario|alquiler temporal|temporada|por día|por dias|diario|por semana|semanal|quincena|quincenal|estadía|estadia|mínimo.*días|minimo.*dias|noches|por noche",
    case=False,
    na=False,
    regex=True
)

print("Registros temporarios:", df_clean["es_temporario"].sum())

Registros temporarios: 8486

In [38]:
# Revisa los precios menores a USD 100 que fueron 
# identificados como temporarios.
print(
    df_clean.loc[
        (df_clean["price_value"] < 100) &
        (df_clean["es_temporario"]) &
        (df_clean["currency"] == "USD"),
        ["id", "Price", "price_value", "currency", "Description"]
    ].head(10)
)

             id   Price  price_value currency  \
4619   51859888  USD 35         35.0      USD
5591   52998715   USD 1          1.0      USD
9370   53954385   USD 1          1.0      USD
9691   45216635   USD 1          1.0      USD
16605  52873487  USD 33         33.0      USD
17996  54240311  USD 27         27.0      USD
18068  54555476  USD 15         15.0      USD
19879  45216635   USD 1          1.0      USD
22161  53954385   USD 1          1.0      USD
22731  52998715   USD 1          1.0      USD

                                             Description
4619   disponible A partir de noviembre del 2024alqui...
5591   Alquiler temporario €1300. - Hermoso depto amo...
9370   Excelente Unidad de: Pallier privado, Excelent...
9691   Reservado. Excelente Piso alto en una de las m...
16605  Hermoso 2 ambientes piso 12, cochera optativa,...
17996  Alquiler temporal – departamento 1 ambiente am...
18068  Alquiler temporal. Miller 2345, 6 C, Villa Urq...
19879  Reservado. Excelente Piso alto en una de las m...
22161  Excelente Unidad de: Pallier privado, Excelent...
22731  Alquiler temporario €1300. - Hermoso depto amo...

In [39]:
#Busca precios USD menores a 100 que no fueron clasificados
# como temporarios.
print(
    df_clean.loc[
        (df_clean["price_value"] < 100) &
        (df_clean["currency"] == "USD") &
        (~df_clean["es_temporario"]),
        ["id", "Price", "price_value", "Description"]
    ].head(20).to_string()
)

             id   Price  price_value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Description
907    53814999   USD 1          1.0  Torres evoque belgrano Recien terminado. En lote con entrada por dos calles, este tres ambientes tiene una amplia terraza y es muy luminoso. Luminoso 2 ambientes en piso alto. El departamento cuenta con hall de entrada, cerradura inteligente, cocina integrada, living-comedor, balcón y muy buena vista. Mts2 cubiertos: 43. 50, Balcón: 2. 50, Amenities: 3. 68. Total para la unidad: 49. 68. El edificio cuenta con pileta cubierta y descubierta con solarium. Gym muy bien equipado con espacio descubierto. Spa con sauna seco, humedo y sala de relax. Sala de masajes. Sala de reuniones. Sum muy bien equipado con mesa de comedor y un living, smart tv, cocina equipada, vajilla. Parrillas tambien equipadas. Sala de adolecentes con mini ping-pong y metegol. Juegos para niños. Categoría. Seguridad 24 hs. Entrada con reconocimiento facial. Mts2 cubiertos: 58, Balcón: 4, Terraza: 48, Amenities: 9. Total para la unidad: 118. 80. Consultar otras tipologías. El monto de alquiler no incluye gastos. nota legal. La información contenida en el presente aviso es meramente a título informativo. Las medidas y superficies son aproximadas y no resultan vinculantes. Los datos definitivos son los que surgen del título de propiedad. Los montos de expensas, tasas e impuestos deben ser confirmados ya que dependen de la fecha en la que se obtuvo la información. El valor indicado en el presente puede ser modificado sin previo aviso. En relación a las unidades en proceso de construcción y/o a estrenar, se deja constancia que las superficies expresadas poseen m2 de amenities y no pueden ser consideradas como definitivas. Las fechas de posesión son estimativas y pueden ser reprogramadas por parte de la dirección de obra. Venta supeditada al cumplimiento por parte del propietario de los requisitos de la resolución general nº 2371 de la Afip (pedido de coti) . “Para los casos de alquiler de vivienda por 3 años, el monto máximo de comisión que se le puede requerir a los propietarios será el equivalente al cuatro con quince centésimos por ciento (4, 15%) del valor total del respectivo contrato. Se encuentra prohibido cobrar a los inquilinos que sean personas físicas comisiones inmobiliarias y gastos de gestoría de informes” (agregado ley 5859) C. U. C. I. C. B. A. Mats. 5179Gaston Matera - Matrícula C. U. C. I. C. B. A N°5179 La Pampa 2055 caba - 11 Ver datos- Matricula Provincia cmzc 576 notas legales: &quot;Ningún inmueble publicado por esta inmobiliaria cuenta con accesibilidad para personas con movilidad reducida (Ley 5115) salvo que se indique expresamente en la descripción de cada ficha”“Para los casos de alquiler de vivienda, el monto máximo de comisión que se le puede requerir a los propietarios será el equivalente al cuatro con quince centésimos por ciento (4, 15%) del valor total del respectivo contrato. Se encuentra prohibido cobrar a los inquilinos que sean personas físicas comisiones inmobiliarias y gastos de gestoría de informes”. -La información contenida en el presente aviso es meramente a título informativo. Las medidas y superficies son aproximadas y no resultan vinculantes. Los datos definitivos son los que surgen del título de propiedad. Los montos de expensas, tasas e impuestos deben ser confirmados ya que dependen de la fecha en la que se obtuvo la información. El valor indicado en el presente puede ser modificado sin previo aviso. En relación a las unidades en proceso de construcción y/o a estrenar, se deja constancia que las superficies expresadas poseen m2 de amenities y no pueden ser consideradas como definitivas. Las fechas de posesión son estimativas y pueden ser reprogramadas por parte de la dirección de obra. Venta supeditada al cumplimiento por parte del propietario de los requisitos de la resolución general nº 2371 de la Afip (pedido de coti) .
5853   53665764  USD 90         90.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Departamento recoleta se encuentra en Buenos Aires, a 1, 8 km de Museo Nacional de Bellas Artes y a 2, 4 km de Museo de Arte Latinoamericano de Buenos Aires (Malba), y ofrece alojamiento con equipamiento como wifi gratis y tv de pantalla plana. Este departamento está a 2, 7 km de Jardín Japonés, Buenos Aires y a 3 km de Plaza Serrano, equipado con aire acondicionado, calefacción y otros, tiene acceso directo a un balcón y cuenta con 2 dormitorios independientes, 3 baños y cocina totalmente equipada. Teatro Colón está a 3, 5 km del alojamiento, y Bosques de Palermo está a 3, 8 km. El aeropuerto más cercano (Aeroparque Jorge Newbery) está a 5 km del alojamiento.
8639   42051719   USD 1          1.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Reservado. Semipiso de categoria ubicado en esquina de 200 m2 emplazado en el Edificio Aleph, construido por Faena group y diseñado por el Arq. Norman Foster. Excelente vista abierta hacia el dique y Petrona Eyle, desde allí se puede ver gran parte de Puerto Madero. Precio paquete, totalmente amoblado y equipado. Se accede por un palier privado a un hall de distribución, posee toilette de recepción, amplio Living Comedor con cocina de concepto abierto y muebles de Silestone, isla central y lavadero incorporado. Electrodomésticos de acero inoxidable. Amplias terrazas perimetrales en todo el departamento. Posee techos altos con bovedilla en todo el departamento, excelente calidad de terminación, aberturas de doble vidrio, baños de mármol. Cortinas eléctricas en todo el departamento. Impecable. Edificio Aleph está ubicado en Petrona Eyle 355, Dique 2 con 11 pisos de los cuales 9 son para viviendas y los dos últimos están destinados a los amenities ( solarium, gimnasio y piscina). Tiene dos subsuelos de cocheras. Complejo compuesto por 50 departamentos en total que llegan hasta los 700 metros las unidades mas grandes. La unidad cuenta con una cochera. Consultar por otras opciones en el edificio tanto de Alquiler como Venta. Tasaciones en el dia.
9681   47676918   USD 1          1.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Alquilado. Excelente departamento de 3 ambientes, en el edificio Forum de Puerto Madero. Vista abierta al Rio con orientación este. Entrando al departamento tenemos un amplio hall con toilette de Recepcion y placard recibidor. Este hall desemboca en el Living-Comedor con cocina de concepto abierto. La cocina tiene mesadas e isla de mármol de carrara y lugar bajo la isla para lavarropas y lavavajillas. El gran Living Comedor termina en un amplio balcon con vista verde, abierta sobre Juana Manso. Un dormitorio en suite con vestidor y vista a los jardines del edificio y la master suite da al frente con grandes ventanales, baño con hidro y un gran vestidor. El departamento esta amoblado, pero opcionalmente se alquila sin muebles. El edificio tiene Cancha de squash, solarium con piletas, Gimnasio, Sum, vestuarios con sauna y lugar para masajes, Cine, Business Center, y pileta de natación cubierta semi olímpica. Este departamento cuenta con cochera y en el edificio hay cocheras de cortesía.

## Identificación de referencias a alquileres anuales

Algunas publicaciones pueden mostrar en el precio un importe correspondiente al primer año, segundo año o al valor anual.

Se crea una variable para identificar estas referencias en la descripción y evitar interpretar automáticamente estos importes como alquileres mensuales.

In [40]:
# Detecta descripciones que mencionan valores anuales o por año.
df_clean["es_anual"] = df_clean["Description"].str.contains(
    r"alquiler anual|alquileres anual|valor primer año|primer año.*usd|segundo año",
    case=False,
    na=False,
    regex=True
)

print("Registros posiblemente anuales:", df_clean["es_anual"].sum())

Registros posiblemente anuales: 317

In [41]:
# Muestra ejemplos de publicaciones clasificadas como 
# posiblemente anuales.
print(
    df_clean.loc[
        df_clean["es_anual"],
        ["id", "Price", "price_value", "currency", "Description"]
    ].head(20)
)

            id      Price  price_value currency  \
225   54097984    USD 850        850.0      USD
343   42729934  USD 2.200       2200.0      USD
362   54370065  USD 1.100       1100.0      USD
434   54173435  USD 2.500       2500.0      USD
669   53546577    USD 900        900.0      USD
937   54537339    USD 400        400.0      USD
2020  54389190  USD 1.400       1400.0      USD
2133  53921263    USD 650        650.0      USD
2566  54066234  $ 450.000     450000.0        $
2695  54097992    USD 750        750.0      USD
3252  54248863    USD 900        900.0      USD
3575  54350498  USD 1.000       1000.0      USD
3788  54214047  $ 350.000     350000.0        $
3795  42561335  $ 380.000     380000.0        $
3941  51566423    USD 550        550.0      USD
4014  53639373  USD 2.000       2000.0      USD
4143  53989645    USD 750        750.0      USD
4155  54263226    USD 650        650.0      USD
4156  54520792  $ 399.000     399000.0        $
4161  54274177    USD 550        550.0      USD

                                            Description
225   Luminoso depto en excelente ubicacion en calle...
343   Superficie Total: 156 m2. Superficie Cubierta:...
362   Departamento reciclado A nuevo en alquiler de ...
434   Divino piso en Torre Clorindo Testa con amplio...
669   Alquiler anual con muebles. Piso con balcón al...
937   Alquiler anual en caballito monoambiente ampli...
2020  Exclusiva Torre de 36 pisos con las mejores vi...
2133  Castex y SalgueroExcelente ubicación a metros ...
2566  ¡Descubrí tu nuevo hogar en el corazón de San ...
2695  Luminoso depto en excelente ubicacion en calle...
3252  Alquiler anual - A estrenar Amplio monoambient...
3575  Alquiler Anual con MueblesEdificio los GalgosP...
3788  Ver descripción, condiciones Y requisitos: Mon...
3795  Dueño alquila monoambiente divisible de 7 años...
3941  Luminoso y ventilado 3 ambientes en Billinghur...
4014  Semipiso estilo francés todo externo con 8 ven...
4143  Alquiler anual para 1 O 2 personas Depto de 3 ...
4155  Corredor Responsable: mauro marvisi csi 5574 /...
4156  Alquiler anual de luminoso monoambiente con co...
4161  En alquilertotalmente equipadopara entrar ya!!...

## Revisión de precios USD menores a 100

Los valores inferiores a USD 100 pueden corresponder a alquileres temporarios, importes parciales, referencias dentro de la descripción u otros casos particulares.

Por este motivo, no se eliminan automáticamente y se revisan según el contexto de cada publicación.

In [42]:
# Identifica precios USD menores a 100 para su revisión.
df_clean["precio_usd_sospechoso"] = (
    (df_clean["currency"] == "USD") &
    (df_clean["price_value"] < 100)
)

print(
    "Precios USD menores a 100:",
    df_clean["precio_usd_sospechoso"].sum()
)

Precios USD menores a 100: 34

In [43]:
# Muestra algunos casos sospechosos junto con su contexto.
df_clean.loc[
    df_clean["precio_usd_sospechoso"],
    ["id", "Price", "price_value", "es_anual", "es_temporario", "Description"]
].head(20)

,id,Price,price_value,es_anual,es_temporario,Description
907,53814999,USD 1,1.0,False,False,Torres evoque belgrano Recien terminado. En lo...
4619,51859888,USD 35,35.0,False,True,disponible A partir de noviembre del 2024alqui...
5591,52998715,USD 1,1.0,False,True,Alquiler temporario €1300. - Hermoso depto amo...
5853,53665764,USD 90,90.0,False,False,Departamento recoleta se encuentra en Buenos A...
8639,42051719,USD 1,1.0,False,False,Reservado. Semipiso de categoria ubicado en es...
9370,53954385,USD 1,1.0,False,True,"Excelente Unidad de: Pallier privado, Excelent..."
9681,47676918,USD 1,1.0,False,False,Alquilado. Excelente departamento de 3 ambient...
9691,45216635,USD 1,1.0,False,True,Reservado. Excelente Piso alto en una de las m...
14218,53814999,USD 1,1.0,False,False,Torres evoque belgrano Recien terminado. En lo...
16605,52873487,USD 33,33.0,False,True,"Hermoso 2 ambientes piso 12, cochera optativa,..."
17996,54240311,USD 27,27.0,False,True,Alquiler temporal – departamento 1 ambiente am...
18068,54555476,USD 15,15.0,False,True,"Alquiler temporal. Miller 2345, 6 C, Villa Urq..."
19879,45216635,USD 1,1.0,False,True,Reservado. Excelente Piso alto en una de las m...
19969,42051719,USD 1,1.0,False,False,Reservado. Semipiso de categoria ubicado en es...
20438,47676918,USD 1,1.0,False,False,Alquilado. Excelente departamento de 3 ambient...
22161,53954385,USD 1,1.0,False,True,"Excelente Unidad de: Pallier privado, Excelent..."
22731,52998715,USD 1,1.0,False,True,Alquiler temporario €1300. - Hermoso depto amo...
25096,53665764,USD 90,90.0,False,False,Departamento recoleta se encuentra en Buenos A...
30821,54555476,USD 15,15.0,False,True,"Alquiler temporal. Miller 2345, 6 C, Villa Urq..."
33048,54592827,USD 1,1.0,False,False,Torres evoque belgrano Recien terminado. En lo...

## Identificación de posibles publicaciones de venta

Algunas publicaciones presentan precios elevados en dólares y contienen referencias explícitas a operaciones de venta.

Se crea una variable auxiliar para identificar estas publicaciones y evitar que puedan distorsionar el análisis de alquileres.

In [44]:
# Detecta menciones de venta dentro de las descripciones.
df_clean["menciona_venta"] = df_clean["Description"].str.contains(
    r"\bventa\b|en venta|precio venta|venta directa|venta urgente|venta con renta",
    case=False,
    na=False,
    regex=True
)

print("Registros que mencionan venta:", df_clean["menciona_venta"].sum())

Registros que mencionan venta: 4034

In [45]:
# Identifica los precios USD elevados que además mencionan venta.
usd_altos_venta = df_clean.loc[
    (df_clean["currency"] == "USD") &
    (df_clean["price_value"] >= 10_000) &
    (df_clean["menciona_venta"]),
    ["id", "Price", "price_value", "Location", "Features", "Description"]
]

print(
    "USD >= 10.000 que mencionan venta:",
    len(usd_altos_venta)
)

USD >= 10.000 que mencionan venta: 60

In [46]:
# Resume cómo se clasifican los precios USD elevados según las 
# variables detectadas.
print(
    df_clean.loc[
        (df_clean["currency"] == "USD") &
        (df_clean["price_value"] >= 10_000),
        ["es_anual", "es_temporario", "menciona_venta"]
    ].value_counts()
)

es_anual  es_temporario  menciona_venta
False     False          False             144
          True           False             137
                         True               35
          False          True               25
True      False          False               4
Name: count, dtype: int64

## Clasificación de posibles publicaciones de venta

Se define una condición para identificar publicaciones que cumplen simultáneamente con tres características:

- Precio expresado en USD.
- Precio igual o superior a USD 10.000.
- Mención de venta en la descripción.

Estas publicaciones se consideran posibles casos de venta y se mantienen identificadas para decidir posteriormente cómo tratarlas en el análisis.

In [47]:
# Marca los registros que cumplen las condiciones 
# definidas como posibles ventas.

df_clean["posible_venta"] = (
    df_clean["currency"].eq("USD") &
    (df_clean["price_value"] >= 10_000) &
    df_clean["menciona_venta"]
)

print(
    "Posibles publicaciones de venta:",
    df_clean["posible_venta"].sum()
)

Posibles publicaciones de venta: 60

In [48]:
# Revisa ejemplos de publicaciones clasificadas como posibles ventas.
print(
    df_clean.loc[
        df_clean["posible_venta"],
        ["id", "Price", "price_value", "Location", "Features"]
    ].head(20).to_string()
)

             id        Price  price_value                        Location                                          Features
22     54364385   USD 10.000      10000.0       Belgrano, Capital Federal  [578 m² tot., 6 amb., 4 dorm., 4 baños, 2 coch.]
456    54440260   USD 20.000      20000.0          Palermo Chico, Palermo  [400 m² tot., 5 amb., 3 dorm., 3 baños, 3 coch.]
471    52718463   USD 20.000      20000.0          Palermo Chico, Palermo  [397 m² tot., 8 amb., 3 dorm., 3 baños, 3 coch.]
984    54527431   USD 15.000      15000.0          Barrio Parque, Palermo  [278 m² tot., 5 amb., 3 dorm., 3 baños, 3 coch.]
1027   52144345   USD 11.000      11000.0          Palermo Chico, Palermo  [400 m² tot., 5 amb., 4 dorm., 6 baños, 3 coch.]
1153   52536584   USD 10.000      10000.0       Recoleta, Capital Federal  [380 m² tot., 7 amb., 4 dorm., 4 baños, 1 coch.]
1878   54281958  USD 140.000     140000.0            Las Cañitas, Palermo             [52 m² tot., 3 amb., 2 dorm., 1 baño]
2092   52886421   USD 10.000      10000.0       Belgrano, Capital Federal  [350 m² tot., 6 amb., 4 dorm., 5 baños, 2 coch.]
5941   53927605   USD 12.000      12000.0  Puerto Madero, Capital Federal  [257 m² tot., 4 amb., 3 dorm., 5 baños, 2 coch.]
5995   53824634   USD 10.000      10000.0       Belgrano, Capital Federal  [357 m² tot., 5 amb., 3 dorm., 3 baños, 2 coch.]
6629   53578978   USD 28.000      28000.0  Puerto Madero, Capital Federal  [485 m² tot., 6 amb., 5 dorm., 6 baños, 4 coch.]
6744   53509457   USD 15.000      15000.0  Puerto Madero, Capital Federal  [425 m² tot., 6 amb., 4 dorm., 5 baños, 2 coch.]
9007   53305151   USD 13.000      13000.0  Puerto Madero, Capital Federal  [183 m² tot., 4 amb., 3 dorm., 4 baños, 2 coch.]
9012   53293067   USD 25.000      25000.0  Puerto Madero, Capital Federal  [495 m² tot., 7 amb., 4 dorm., 4 baños, 4 coch.]
9279   51397096   USD 16.500      16500.0  Puerto Madero, Capital Federal  [435 m² tot., 5 amb., 4 dorm., 3 baños, 3 coch.]
10158  54526021   USD 15.000      15000.0          Barrio Parque, Palermo  [397 m² tot., 5 amb., 3 dorm., 3 baños, 3 coch.]
13884  52718463   USD 20.000      20000.0          Palermo Chico, Palermo  [397 m² tot., 8 amb., 3 dorm., 3 baños, 3 coch.]
13896  52536584   USD 10.000      10000.0       Recoleta, Capital Federal  [380 m² tot., 7 amb., 4 dorm., 4 baños, 1 coch.]
14197  54527431   USD 15.000      15000.0          Barrio Parque, Palermo  [278 m² tot., 5 amb., 3 dorm., 3 baños, 3 coch.]
14358  54440260   USD 20.000      20000.0          Palermo Chico, Palermo  [400 m² tot., 5 amb., 3 dorm., 3 baños, 3 coch.]

In [49]:
# Comprueba la cantidad de publicaciones y propiedades 
# únicas detectadas.
print(
    "Registros posibles venta:",
    df_clean["posible_venta"].sum()
)

print(
    "IDs únicos:",
    df_clean.loc[
        df_clean["posible_venta"],
        "id"
    ].nunique()
)

Registros posibles venta: 60
IDs únicos: 24

## Revisión de posibles ventas repetidas

Un mismo inmueble puede aparecer en distintas fechas de scraping. Por lo tanto, se analiza la frecuencia de los `id` identificados como posibles ventas para distinguir entre publicaciones repetidas y propiedades diferentes.

In [50]:
# Cuenta cuántas veces aparece cada propiedad entre 
# las posibles ventas.
duplicados_venta = (
    df_clean.loc[df_clean["posible_venta"], "id"]
    .value_counts()
)

print(duplicados_venta)

id
53824634    4
53578978    4
53509457    4
53305151    4
53293067    4
52718463    3
54527431    3
52144345    3
52536584    3
54281958    3
52886421    3
53927605    3
51397096    3
54526021    3
54440260    2
53716204    2
54554374    2
54364385    1
54572897    1
55151490    1
55265276    1
53639014    1
50416649    1
56662123    1
Name: count, dtype: int64

In [51]:
# Obtiene todos los IDs correspondientes a posibles ventas.
ids_venta = df_clean.loc[
    df_clean["posible_venta"],
    "id"
].unique()

In [52]:
# Comprueba cuántas veces aparece cada propiedad en todo el dataset.
print(
    df_clean[
        df_clean["id"].isin(ids_venta)
    ]["id"].value_counts()
)

id
53824634    4
53578978    4
53509457    4
53305151    4
53293067    4
50416649    4
54440260    3
52718463    3
54527431    3
52144345    3
52536584    3
54281958    3
52886421    3
53927605    3
51397096    3
54526021    3
53716204    2
54554374    2
54364385    1
54572897    1
55151490    1
55265276    1
53639014    1
56662123    1
Name: count, dtype: int64

In [53]:
# Compara las apariciones de cada propiedad a través de 
# las fechas de scraping.
print(
    df_clean[
        df_clean["id"].isin(ids_venta)
    ][
        ["id", "Price", "Location", "scrap_date"]
    ].sort_values("id").to_string()
)

             id             Price                        Location                 scrap_date
20150  50416649         USD 9.500          Palermo Chico, Palermo 2024-09-24 12:26:30.907747
51365  50416649        USD 14.500          Palermo Chico, Palermo 2025-03-09 00:26:57.589025
38574  50416649         USD 9.500          Palermo Chico, Palermo 2024-09-29 23:47:13.054893
9816   50416649         USD 9.500          Palermo Chico, Palermo 2024-09-23 08:28:14.272951
33285  51397096        USD 16.500  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
19792  51397096        USD 16.500  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
9279   51397096        USD 16.500  Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
1027   52144345        USD 11.000          Palermo Chico, Palermo 2024-09-23 08:28:14.272951
14581  52144345        USD 11.000          Palermo Chico, Palermo 2024-09-24 12:26:30.907747
28525  52144345        USD 11.000          Palermo Chico, Palermo 2024-09-29 23:47:13.054893
41833  52536584        USD 10.000       Recoleta, Capital Federal 2025-03-09 00:26:57.589025
1153   52536584        USD 10.000       Recoleta, Capital Federal 2024-09-23 08:28:14.272951
13896  52536584        USD 10.000       Recoleta, Capital Federal 2024-09-24 12:26:30.907747
471    52718463        USD 20.000          Palermo Chico, Palermo 2024-09-23 08:28:14.272951
28792  52718463        USD 20.000          Palermo Chico, Palermo 2024-09-29 23:47:13.054893
13884  52718463        USD 20.000          Palermo Chico, Palermo 2024-09-24 12:26:30.907747
16139  52886421        USD 10.000       Belgrano, Capital Federal 2024-09-24 12:26:30.907747
29232  52886421        USD 10.000       Belgrano, Capital Federal 2024-09-29 23:47:13.054893
2092   52886421        USD 10.000       Belgrano, Capital Federal 2024-09-23 08:28:14.272951
34725  53293067        USD 25.000  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
23082  53293067        USD 25.000  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
50689  53293067        USD 25.000  Puerto Madero, Capital Federal 2025-03-09 00:26:57.589025
9012   53293067        USD 25.000  Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
9007   53305151        USD 13.000  Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
37768  53305151        USD 13.000  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
45796  53305151        USD 10.000  Puerto Madero, Capital Federal 2025-03-09 00:26:57.589025
26698  53305151        USD 13.000  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
22773  53509457        USD 15.000  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
37679  53509457        USD 15.000  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
51451  53509457        USD 17.000  Puerto Madero, Capital Federal 2025-03-09 00:26:57.589025
6744   53509457        USD 15.000  Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
6629   53578978        USD 28.000  Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
34866  53578978        USD 28.000  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
23213  53578978        USD 28.000  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
51481  53578978        USD 28.000  Puerto Madero, Capital Federal 2025-03-09 00:26:57.589025
44762  53639014        USD 10.000       Recoleta, Capital Federal 2025-03-09 00:26:57.589025
31840  53716204        USD 15.000  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
18876  53716204        USD 15.000  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
48705  53824634        USD 10.000       Belgrano, Capital Federal 2025-03-09 00:26:57.589025
38433  53824634        USD 10.000       Belgrano, Capital Federal 2024-09-29 23:47:13.054893
5995   53824634        USD 10.000       Belgrano, Capital Federal 2024-09-23 08:28:14.272951
25086  53824634        USD 10.000       Belgrano, Capital Federal 2024-09-24 12:26:30.907747
36644  53927605        USD 12.000  Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
22013  53927605        USD 12.000  Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
5941   53927605        USD 12.000  Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
16061  54281958       USD 140.000            Las Cañitas, Palermo 2024-09-24 12:26:30.907747
29907  54281958       USD 140.000            Las Cañitas, Palermo 2024-09-29 23:47:13.054893
1878   54281958       USD 140.000            Las Cañitas, Palermo 2024-09-23 08:28:14.272951
22     54364385        USD 10.000       Belgrano, Capital Federal 2024-09-23 08:28:14.272951
28614  54440260  Consultar precio          Palermo Chico, Palermo 2024-09-29 23:47:13.054893
14358  54440260        USD 20.000          Palermo Chico, Palermo 2024-09-24 12:26:30.907747
456    54440260        USD 20.000          Palermo Chico, Palermo 2024-09-23 08:28:14.272951
37149  54526021        USD 15.000          Barrio Parque, Palermo 2024-09-29 23:47:13.054893
24849  54526021        USD 15.000          Barrio Parque, Palermo 2024-09-24 12:26:30.907747
10158  54526021        USD 15.000          Barrio Parque, Palermo 2024-09-23 08:28:14.272951
28530  54527431        USD 15.000          Barrio Parque, Palermo 2024-09-29 23:47:13.054893
14197  54527431        USD 15.000          Barrio Parque, Palermo 2024-09-24 12:26:30.907747
984    54527431        USD 15.000          Barrio Parque, Palermo 2024-09-23 08:28:14.272951
33012  54554374        USD 10.000       Belgrano, Capital Federal 2024-09-29 23:47:13.054893
19162  54554374        USD 10.000       Belgrano, Capital Federal 2024-09-24 12:26:30.907747
37431  54572897       USD 172.000       Belgrano, Capital Federal 2024-09-29 23:47:13.054893
42373  55151490        USD 10.000            Las Cañitas, Palermo 2025-03-09 00:26:57.589025
43294  55265276        USD 12.000  Puerto Madero, Capital Federal 2025-03-09 00:26:57.589025
55608  56662123        USD 30.000  Puerto Madero, Capital Federal 2025-07-12 13:35:44.207335

## Análisis de cambios de precio

Como una misma propiedad puede aparecer en diferentes fechas de scraping, se analiza si el precio registrado para un mismo `id` cambia con el tiempo.

Esto permite diferenciar entre duplicados producto del proceso de scraping y modificaciones reales en la publicación.

In [54]:
# Cuenta cuántos precios distintos tuvo cada propiedad.
cambios_precio = (
    df_clean
    .groupby("id")["price_value"]
    .nunique()
)

print(
    "IDs con más de un precio:",
    (cambios_precio > 1).sum()
)

IDs con más de un precio: 1656

In [55]:
# Muestra las propiedades con mayor cantidad de precios diferentes.
print(
    cambios_precio[cambios_precio > 1]
    .sort_values(ascending=False)
    .head(20)
)

id
49198709    3
51812945    3
52948562    3
47815746    3
54101372    3
53447276    3
53717898    3
50010131    3
53148995    3
51474128    3
52277547    3
46213977    3
54260350    3
53684700    3
53632473    3
46745535    3
54277850    3
52320768    3
48259210    3
53926993    3
Name: price_value, dtype: int64

In [56]:
# Selecciona las propiedades cuyos precios cambiaron para revisar su 
# evolución temporal.
ids_cambio_precio = cambios_precio[cambios_precio > 1].index

cambios = (
    df_clean[df_clean["id"].isin(ids_cambio_precio)]
    [["id", "Price", "price_value", "currency", "Location", "scrap_date"]]
    .sort_values(["id", "scrap_date"])
)

In [57]:
# Muestra ejemplos de cambios de precio ordenados cronológicamente.

print(
    cambios.head(50).to_string(index=False)
)

      id      Price  price_value currency                       Location                 scrap_date
29065562 USD 10.000      10000.0      USD         Palermo Nuevo, Palermo 2024-09-23 08:28:14.272951
29065562 USD 10.000      10000.0      USD         Palermo Nuevo, Palermo 2024-09-24 12:26:30.907747
29065562 USD 10.000      10000.0      USD         Palermo Nuevo, Palermo 2024-09-29 23:47:13.054893
29065562 USD 12.000      12000.0      USD         Palermo Nuevo, Palermo 2025-03-09 00:26:57.589025
32087467  $ 360.000     360000.0        $        Abasto, Capital Federal 2024-09-23 08:28:14.272951
32087467  $ 360.000     360000.0        $        Abasto, Capital Federal 2024-09-24 12:26:30.907747
32087467  $ 360.000     360000.0        $        Abasto, Capital Federal 2024-09-29 23:47:13.054893
32087467  $ 400.000     400000.0        $        Abasto, Capital Federal 2025-03-09 00:26:57.589025
32670060    USD 500        500.0      USD     Monserrat, Capital Federal 2024-09-23 08:28:14.272951
32670060    USD 500        500.0      USD     Monserrat, Capital Federal 2024-09-24 12:26:30.907747
32670060    USD 450        450.0      USD     Monserrat, Capital Federal 2024-09-29 23:47:13.054893
41038893  $ 450.000     450000.0        $     Palermo Hollywood, Palermo 2024-09-23 08:28:14.272951
41038893  $ 450.000     450000.0        $     Palermo Hollywood, Palermo 2024-09-24 12:26:30.907747
41038893  $ 450.000     450000.0        $     Palermo Hollywood, Palermo 2024-09-29 23:47:13.054893
41038893  $ 550.000     550000.0        $     Palermo Hollywood, Palermo 2025-03-09 00:26:57.589025
41083338    USD 700        700.0      USD       Palermo, Capital Federal 2024-09-23 08:28:14.272951
41083338    USD 700        700.0      USD       Palermo, Capital Federal 2024-09-24 12:26:30.907747
41083338    USD 700        700.0      USD       Palermo, Capital Federal 2024-09-29 23:47:13.054893
41083338    USD 900        900.0      USD       Palermo, Capital Federal 2025-03-09 00:26:57.589025
41227544  $ 300.000     300000.0        $  Barrio Norte, Capital Federal 2024-09-23 08:28:14.272951
41227544  $ 300.000     300000.0        $  Barrio Norte, Capital Federal 2024-09-24 12:26:30.907747
41227544  $ 300.000     300000.0        $  Barrio Norte, Capital Federal 2024-09-29 23:47:13.054893
41227544  $ 290.000     290000.0        $  Barrio Norte, Capital Federal 2025-03-09 00:26:57.589025
41308631  USD 2.000       2000.0      USD Puerto Madero, Capital Federal 2024-09-23 08:28:14.272951
41308631  USD 2.000       2000.0      USD Puerto Madero, Capital Federal 2024-09-24 12:26:30.907747
41308631  USD 1.800       1800.0      USD Puerto Madero, Capital Federal 2024-09-29 23:47:13.054893
41326050  $ 500.000     500000.0        $         Palermo Viejo, Palermo 2024-09-23 08:28:14.272951
41326050  $ 500.000     500000.0        $         Palermo Viejo, Palermo 2024-09-24 12:26:30.907747
41326050  $ 500.000     500000.0        $         Palermo Viejo, Palermo 2024-09-29 23:47:13.054893
41326050    USD 500        500.0      USD         Palermo Viejo, Palermo 2025-03-09 00:26:57.589025
41429495    USD 750        750.0      USD     Palermo Hollywood, Palermo 2024-09-23 08:28:14.272951
41429495    USD 750        750.0      USD     Palermo Hollywood, Palermo 2024-09-24 12:26:30.907747
41429495    USD 700        700.0      USD     Palermo Hollywood, Palermo 2024-09-29 23:47:13.054893
41450957    USD 345        345.0      USD       Palermo, Capital Federal 2024-09-23 08:28:14.272951
41450957    USD 345        345.0      USD       Palermo, Capital Federal 2024-09-24 12:26:30.907747
41450957    USD 350        350.0      USD       Palermo, Capital Federal 2024-09-29 23:47:13.054893
41450957  $ 470.000     470000.0        $       Palermo, Capital Federal 2025-03-09 00:26:57.589025
41479516  $ 595.000     595000.0        $       Palermo, Capital Federal 2024-09-23 08:28:14.272951
41479516  $ 595.000     595000.0        $       Palermo, Capital Federal 2024-09-24 12:26:30.907747
41479516  $ 499.000     499000.0        $       Palermo, Capital Federal 2025-03-09 00:26:57.589025
41839545    USD 850        850.0      USD     Palermo Hollywood, Palermo 2024-09-23 08:28:14.272951
41839545    USD 850        850.0      USD     Palermo Hollywood, Palermo 2024-09-24 12:26:30.907747
41839545    USD 850        850.0      USD     Palermo Hollywood, Palermo 2024-09-29 23:47:13.054893
41839545    USD 900        900.0      USD     Palermo Hollywood, Palermo 2025-03-09 00:26:57.589025
41933761    USD 450        450.0      USD     Palermo Hollywood, Palermo 2024-09-23 08:28:14.272951
41933761    USD 450        450.0      USD     Palermo Hollywood, Palermo 2024-09-24 12:26:30.907747
41933761  $ 650.000     650000.0        $     Palermo Hollywood, Palermo 2024-09-29 23:47:13.054893
42142767  $ 700.000     700000.0        $    Tribunales, Capital Federal 2024-09-23 08:28:14.272951
42142767  $ 700.000     700000.0        $    Tribunales, Capital Federal 2024-09-24 12:26:30.907747
42142767  $ 700.000     700000.0        $    Tribunales, Capital Federal 2024-09-29 23:47:13.054893

## Análisis de cambios de moneda

Se analiza si una misma propiedad aparece registrada en diferentes monedas a lo largo de las fechas de scraping.

Estos casos requieren especial atención porque un cambio entre pesos y dólares puede generar diferencias aparentes muy grandes en `price_value` que no representan necesariamente una modificación equivalente del alquiler.

In [58]:
# Cuenta cuántas monedas distintas aparecen para cada propiedad.
cambios_moneda = (
    df_clean
    .groupby("id")["currency"]
    .nunique()
)

print(
    "IDs con más de una moneda:",
    (cambios_moneda > 1).sum()
)

IDs con más de una moneda: 106

In [59]:
# Muestra las propiedades que presentan cambios de moneda.
print(
    cambios_moneda[cambios_moneda > 1]
    .sort_values(ascending=False)
    .head(20)
)

id
41326050    2
41450957    2
41933761    2
42796426    2
44697653    2
46770741    2
47815746    2
48389367    2
48682166    2
50828216    2
50912156    2
51319366    2
51364046    2
51382503    2
51566423    2
51728468    2
51812945    2
51836541    2
52170360    2
52277547    2
Name: currency, dtype: int64

In [60]:
# Selecciona las propiedades con cambios de moneda para revisar su evolución.
ids_cambio_moneda = cambios_moneda[cambios_moneda > 1].index

cambios_moneda_detalle = (
    df_clean[df_clean["id"].isin(ids_cambio_moneda)]
    [["id", "Price", "price_value", "currency", "Location", "scrap_date"]]
    .sort_values(["id", "scrap_date"])
)

In [61]:
# Muestra los cambios de moneda junto con la fecha del scraping.
print(
    cambios_moneda_detalle[
        ["id", "Price", "currency", "scrap_date"]
    ].to_string(index=False)
)

      id       Price currency                 scrap_date
41326050   $ 500.000        $ 2024-09-23 08:28:14.272951
41326050   $ 500.000        $ 2024-09-24 12:26:30.907747
41326050   $ 500.000        $ 2024-09-29 23:47:13.054893
41326050     USD 500      USD 2025-03-09 00:26:57.589025
41450957     USD 345      USD 2024-09-23 08:28:14.272951
41450957     USD 345      USD 2024-09-24 12:26:30.907747
41450957     USD 350      USD 2024-09-29 23:47:13.054893
41450957   $ 470.000        $ 2025-03-09 00:26:57.589025
41933761     USD 450      USD 2024-09-23 08:28:14.272951
41933761     USD 450      USD 2024-09-24 12:26:30.907747
41933761   $ 650.000        $ 2024-09-29 23:47:13.054893
42796426   $ 400.000        $ 2024-09-23 08:28:14.272951
42796426   $ 400.000        $ 2024-09-24 12:26:30.907747
42796426   $ 400.000        $ 2024-09-29 23:47:13.054893
42796426     USD 600      USD 2025-03-09 00:26:57.589025
44697653   $ 460.000        $ 2024-09-23 08:28:14.272951
44697653   $ 460.000        $ 2024-09-24 12:26:30.907747
44697653     USD 400      USD 2024-09-29 23:47:13.054893
46770741     USD 500      USD 2024-09-23 08:28:14.272951
46770741     USD 500      USD 2024-09-24 12:26:30.907747
46770741   $ 550.000        $ 2024-09-29 23:47:13.054893
47815746     USD 850      USD 2024-09-23 08:28:14.272951
47815746     USD 850      USD 2024-09-24 12:26:30.907747
47815746     USD 880      USD 2024-09-29 23:47:13.054893
47815746   $ 850.000        $ 2025-03-09 00:26:57.589025
48389367   $ 450.000        $ 2024-09-23 08:28:14.272951
48389367   $ 450.000        $ 2024-09-24 12:26:30.907747
48389367   $ 450.000        $ 2024-09-29 23:47:13.054893
48389367     USD 550      USD 2025-03-09 00:26:57.589025
48682166     USD 500      USD 2024-09-23 08:28:14.272951
48682166     USD 500      USD 2024-09-24 12:26:30.907747
48682166     USD 500      USD 2024-09-29 23:47:13.054893
48682166   $ 600.000        $ 2025-03-09 00:26:57.589025
50828216       $ 950        $ 2024-09-23 08:28:14.272951
50828216       $ 850        $ 2024-09-24 12:26:30.907747
50828216     USD 850      USD 2024-09-29 23:47:13.054893
50912156   $ 650.000        $ 2024-09-23 08:28:14.272951
50912156   $ 650.000        $ 2024-09-24 12:26:30.907747
50912156   $ 650.000        $ 2024-09-29 23:47:13.054893
50912156     USD 550      USD 2025-03-09 00:26:57.589025
51319366   $ 500.000        $ 2024-09-23 08:28:14.272951
51319366   $ 500.000        $ 2024-09-24 12:26:30.907747
51319366   $ 500.000        $ 2024-09-29 23:47:13.054893
51319366     USD 500      USD 2025-03-09 00:26:57.589025
51364046   $ 500.000        $ 2024-09-23 08:28:14.272951
51364046   $ 500.000        $ 2024-09-24 12:26:30.907747
51364046   $ 500.000        $ 2024-09-29 23:47:13.054893
51364046     USD 500      USD 2025-03-09 00:26:57.589025
51382503     USD 350      USD 2024-09-23 08:28:14.272951
51382503     USD 350      USD 2024-09-24 12:26:30.907747
51382503     USD 350      USD 2024-09-29 23:47:13.054893
51382503   $ 450.000        $ 2025-03-09 00:26:57.589025
51566423     USD 550      USD 2024-09-23 08:28:14.272951
51566423     USD 550      USD 2024-09-24 12:26:30.907747
51566423   $ 700.000        $ 2024-09-29 23:47:13.054893
51728468 $ 1.900.000        $ 2024-09-23 08:28:14.272951
51728468 $ 1.900.000        $ 2024-09-24 12:26:30.907747
51728468   USD 1.600      USD 2024-09-29 23:47:13.054893
51812945     USD 750      USD 2024-09-23 08:28:14.272951
51812945     USD 450      USD 2024-09-24 12:26:30.907747
51812945   $ 500.000        $ 2024-09-29 23:47:13.054893
51836541   $ 850.000        $ 2024-09-23 08:28:14.272951
51836541   $ 850.000        $ 2024-09-24 12:26:30.907747
51836541     USD 650      USD 2024-09-29 23:47:13.054893
52170360   $ 900.000        $ 2024-09-23 08:28:14.272951
52170360   $ 900.000        $ 2024-09-24 12:26:30.907747
52170360   $ 900.000        $ 2024-09-29 23:47:13.054893
52170360   USD 1.300      USD 2025-03-09 00:26:57.589025
52277547     USD 400      USD 2024-09-23 08:28:14.272951
52277547     USD 400      USD 2024-09-24 12:26:30.907747
52277547     USD 450      USD 2024-09-29 23:47:13.054893
52277547   $ 500.000        $ 2025-03-09 00:26:57.589025
52320768     USD 900      USD 2024-09-23 08:28:14.272951
52320768     USD 900      USD 2024-09-24 12:26:30.907747
52320768     USD 900      USD 2024-09-29 23:47:13.054893
52320768 $ 1.300.000        $ 2025-03-09 00:26:57.589025
52320768 $ 1.280.000        $ 2025-07-12 13:35:44.207335
52474267     USD 800      USD 2024-09-23 08:28:14.272951
52474267     USD 800      USD 2024-09-24 12:26:30.907747
52474267     USD 800      USD 2024-09-29 23:47:13.054893
52474267 $ 1.200.000        $ 2025-03-09 00:26:57.589025
52474558   $ 330.000        $ 2024-09-23 08:28:14.272951
52474558     USD 350      USD 2024-09-29 23:47:13.054893
52522178     USD 550      USD 2024-09-23 08:28:14.272951
52522178     USD 550      USD 2024-09-24 12:26:30.907747
52522178     USD 550      USD 2024-09-29 23:47:13.054893
52522178   $ 680.000        $ 2025-03-09 00:26:57.589025
53282225   USD 1.800      USD 2024-09-23 08:28:14.272951
53282225   USD 1.800      USD 2024-09-24 12:26:30.907747
53282225   USD 1.800      USD 2024-09-29 23:47:13.054893
53282225   $ 900.000        $ 2025-03-09 00:26:57.589025
53346444   $ 750.000        $ 2024-09-23 08:28:14.272951
53346444   $ 750.000        $ 2024-09-24 12:26:30.907747
53346444   $ 750.000        $ 2024-09-29 23:47:13.054893
53346444     USD 700      USD 2025-03-09 00:26:57.589025
53409528     USD 550      USD 2024-09-23 08:28:14.272951
53409528     USD 550      USD 2024-09-24 12:26:30.907747
53409528   $ 650.000        $ 2024-09-29 23:47:13.054893
53513566     USD 800      USD 2024-09-23 08:28:14.272951
53513566     USD 800      USD 2024-09-24 12:26:30.907747
53513566     USD 800      USD 2024-09-29 23:47:13.054893
53513566   $ 650.000        $ 2025-03-09 00:26:57.589025
53539466     USD 550      USD 2024-09-23 08:28:14.272951
53539466     USD 550      USD 2024-09-24 12:26:30.907747
53539466     USD 550      USD 2024-09-29 23:47:13.054893
53539466   $ 750.000        $ 2025-03-09 00:26:57.589025
53539643     USD 450      USD 2024-09-23 08:28:14.272951
53539643     USD 450      USD 2024-09-24 12:26:30.907747
53539643     USD 450      USD 2024-09-29 23:47:13.054893
53539643   $ 600.000        $ 2025-03-09 00:26:57.589025
53604908   $ 480.000        $ 2024-09-23 08:28:14.272951
53604908   $ 480.000        $ 2024-09-24 12:26:30.907747
53604908   $ 480.000        $ 2024-09-29 23:47:13.054893
53604908     USD 500      USD 2025-03-09 00:26:57.589025
53622525   $ 700.000        $ 2024-09-23 08:28:14.272951
53622525   $ 700.000        $ 2024-09-24 12:26:30.907747
53622525   $ 760.000        $ 2024-09-29 23:47:13.054893
53622525     USD 700      USD 2025-03-09 00:26:57.589025
53652835     USD 500      USD 2024-09-23 08:28:14.272951
53652835     USD 500      USD 2024-09-24 12:26:30.907747
53652835     USD 500      USD 2024-09-29 23:47:13.054893
53652835   $ 800.000        $ 2025-03-09 00:26:57.589025
53655172     USD 350      USD 2024-09-23 08:28:14.272951
53655172     USD 350      USD 2024-09-24 12:26:30.907747
53655172   $ 450.000        $ 2024-09-29 23:47:13.054893
53681099   USD 1.200      USD 2024-09-23 08:28:14.272951
53681099   USD 1.200      USD 2024-09-24 12:26:30.907747
53681099 $ 1.500.000        $ 2024-09-29 23:47:13.054893
53684700     USD 600      USD 2024-09-23 08:28:14.272951
53684700     USD 600      USD 2024-09-24 12:26:30.907747
53684700     USD 600      USD 2024-09-29 23:47:13.054893
53684700     USD 650      USD 2025-03-09 00:26:57.589025
53684700   $ 850.000        $ 2025-07-12 13:35:44.207335
53768020     USD 500      USD 2024-09-23 08:28:14.272951
53768020     USD 500      USD 2024-09-24 12:26:30.907747
53768020     USD 500      USD 2024-09-29 23:47:13.054893
53768020   $ 480.000        $ 2025-03-09 00:26:57.589025
53961492     USD 500      USD 2024-09-23 08:28:14.272951
53961492     USD 500      USD 2024-09-24 12:26:30.907747
53961492     USD 500      USD 2024-09-29 23:47:13.054893
53961492   $ 600.000        $ 2025-03-09 00:26:57.589025
53961868     USD 990      USD 2024-09-23 08:28:14.272951
53961868     USD 990      USD 2024-09-24 12:26:30.907747
53961868     USD 990      USD 2024-09-29 23:47:13.054893
53961868 $ 1.300.000        $ 2025-03-09 00:26:57.589025
53982171     USD 600      USD 2024-09-23 08:28:14.272951
53982171     USD 600      USD 2024-09-24 12:26:30.907747
53982171     USD 600      USD 2024-09-29 23:47:13.054893
53982171   $ 600.000        $ 2025-03-09 00:26:57.589025
54046374     USD 450      USD 2024-09-23 08:28:14.272951
54046374     USD 450      USD 2024-09-24 12:26:30.907747
54046374     USD 450      USD 2024-09-29 23:47:13.054893
54046374   $ 525.000        $ 2025-03-09 00:26:57.589025
54055681       $ 900        $ 2024-09-23 08:28:14.272951
54055681       $ 900        $ 2024-09-24 12:26:30.907747
54055681       $ 900        $ 2024-09-29 23:47:13.054893
54055681     USD 900      USD 2025-03-09 00:26:57.589025
54077418   USD 1.200      USD 2024-09-23 08:28:14.272951
54077418   $ 890.000        $ 2024-09-24 12:26:30.907747
54077418   $ 890.000        $ 2024-09-29 23:47:13.054893
54097009     USD 710      USD 2024-09-24 12:26:30.907747
54097009   $ 920.000        $ 2024-09-29 23:47:13.054893
54101372   $ 350.000        $ 2024-09-23 08:28:14.272951
54101372   $ 350.000        $ 2024-09-24 12:26:30.907747
54101372   $ 300.000        $ 2024-09-29 23:47:13.054893
54101372 USD 450.000      USD 2025-03-09 00:26:57.589025
54117247 $ 1.600.000        $ 2024-09-23 08:28:14.272951
54117247 $ 1.600.000        $ 2024-09-24 12:26:30.907747
54117247   USD 1.300      USD 2024-09-29 23:47:13.054893
54119397     USD 600      USD 2024-09-23 08:28:14.272951
54119397     USD 600      USD 2024-09-24 12:26:30.907747
54119397   $ 700.000        $ 2024-09-29 23:47:13.054893
54156036     USD 750      USD 2024-09-23 08:28:14.272951
54156036     USD 750      USD 2024-09-24 12:26:30.907747
54156036     USD 750      USD 2024-09-29 23:47:13.054893
54156036 $ 1.100.000        $ 2025-03-09 00:26:57.589025
54175000     USD 500      USD 2024-09-23 08:28:14.272951
54175000     USD 500      USD 2024-09-24 12:26:30.907747
54175000   $ 480.000        $ 2024-09-29 23:47:13.054893
54187002     USD 700      USD 2024-09-23 08:28:14.272951
54187002     USD 700      USD 2024-09-24 12:26:30.907747
54187002   $ 800.000        $ 2024-09-29 23:47:13.054893
54196436   USD 2.000      USD 2024-09-23 08:28:14.272951
54196436   USD 2.000      USD 2024-09-24 12:26:30.907747
54196436   USD 2.000      USD 2024-09-29 23:47:13.054893
54196436 $ 1.800.000        $ 2025-03-09 00:26:57.589025
54217880   $ 520.000        $ 2024-09-23 08:28:14.272951
54217880   $ 520.000        $ 2024-09-24 12:26:30.907747
54217880   $ 520.000        $ 2024-09-29 23:47:13.054893
54217880     USD 500      USD 2025-03-09 00:26:57.589025
54221962   USD 2.300      USD 2024-09-23 08:28:14.272951
54221962   USD 2.300      USD 2024-09-24 12:26:30.907747
54221962 $ 2.600.000        $ 2024-09-29 23:47:13.054893
54235946   USD 1.100      USD 2024-09-23 08:28:14.272951
54235946   USD 1.100      USD 2024-09-24 12:26:30.907747
54235946 $ 1.250.000        $ 2024-09-29 23:47:13.054893
54239689 USD 800.000      USD 2024-09-23 08:28:14.272951
54239689 USD 800.000      USD 2024-09-24 12:26:30.907747
54239689   $ 770.000        $ 2024-09-29 23:47:13.054893
54255607     USD 380      USD 2024-09-23 08:28:14.272951
54255607     USD 380      USD 2024-09-24 12:26:30.907747
54255607     USD 380      USD 2024-09-29 23:47:13.054893
54255607   $ 500.000        $ 2025-03-09 00:26:57.589025
54261188   $ 560.000        $ 2024-09-23 08:28:14.272951
54261188   $ 560.000        $ 2024-09-24 12:26:30.907747
54261188     USD 470      USD 2024-09-29 23:47:13.054893
54277850   USD 1.900      USD 2024-09-23 08:28:14.272951
54277850   USD 1.500      USD 2024-09-24 12:26:30.907747
54277850 $ 1.850.000        $ 2024-09-29 23:47:13.054893
54282899     USD 450      USD 2024-09-23 08:28:14.272951
54282899     USD 450      USD 2024-09-24 12:26:30.907747
54282899     USD 450      USD 2024-09-29 23:47:13.054893
54282899   $ 800.000        $ 2025-03-09 00:26:57.589025
54295223   $ 920.000        $ 2025-03-09 00:26:57.589025
54295223     USD 800      USD 2025-07-12 13:35:44.207335
54299395     USD 750      USD 2024-09-23 08:28:14.272951
54299395   $ 850.000        $ 2024-09-24 12:26:30.907747
54299395     USD 750      USD 2024-09-29 23:47:13.054893
54309863     USD 500      USD 2024-09-23 08:28:14.272951
54309863     USD 500      USD 2024-09-24 12:26:30.907747
54309863   $ 550.000        $ 2024-09-29 23:47:13.054893
54312798     USD 550      USD 2024-09-23 08:28:14.272951
54312798     USD 550      USD 2024-09-24 12:26:30.907747
54312798   $ 750.000        $ 2024-09-29 23:47:13.054893
54327095     USD 650      USD 2024-09-23 08:28:14.272951
54327095     USD 650      USD 2024-09-24 12:26:30.907747
54327095     USD 650      USD 2024-09-29 23:47:13.054893
54327095   $ 650.000        $ 2025-03-09 00:26:57.589025
54327422     USD 440      USD 2024-09-23 08:28:14.272951
54327422     USD 440      USD 2024-09-24 12:26:30.907747
54327422     USD 440      USD 2024-09-29 23:47:13.054893
54327422   $ 550.000        $ 2025-03-09 00:26:57.589025
54337037     USD 600      USD 2024-09-23 08:28:14.272951
54337037     USD 600      USD 2024-09-24 12:26:30.907747
54337037   $ 750.000        $ 2024-09-29 23:47:13.054893
54349393   $ 980.000        $ 2024-09-23 08:28:14.272951
54349393   $ 980.000        $ 2024-09-24 12:26:30.907747
54349393     USD 800      USD 2024-09-29 23:47:13.054893
54369540     USD 540      USD 2024-09-23 08:28:14.272951
54369540     USD 540      USD 2024-09-24 12:26:30.907747
54369540     USD 540      USD 2024-09-29 23:47:13.054893
54369540   $ 640.000        $ 2025-03-09 00:26:57.589025
54369540   $ 640.000        $ 2025-07-12 13:35:44.207335
54374088     USD 400      USD 2024-09-23 08:28:14.272951
54374088     USD 380      USD 2024-09-24 12:26:30.907747
54374088   $ 350.000        $ 2024-09-29 23:47:13.054893
54379598     USD 650      USD 2024-09-23 08:28:14.272951
54379598   $ 800.000        $ 2024-09-24 12:26:30.907747
54379598   $ 800.000        $ 2024-09-29 23:47:13.054893
54388466     USD 350      USD 2024-09-23 08:28:14.272951
54388466     USD 350      USD 2024-09-24 12:26:30.907747
54388466     USD 350      USD 2024-09-29 23:47:13.054893
54388466   $ 400.000        $ 2025-03-09 00:26:57.589025
54397522     USD 500      USD 2024-09-23 08:28:14.272951
54397522     USD 500      USD 2024-09-24 12:26:30.907747
54397522   $ 570.000        $ 2024-09-29 23:47:13.054893
54406301     USD 350      USD 2024-09-23 08:28:14.272951
54406301     USD 350      USD 2024-09-24 12:26:30.907747
54406301   $ 450.000        $ 2024-09-29 23:47:13.054893
54406393   USD 1.200      USD 2024-09-23 08:28:14.272951
54406393   USD 1.200      USD 2024-09-24 12:26:30.907747
54406393 $ 1.500.000        $ 2024-09-29 23:47:13.054893
54421718     USD 650      USD 2024-09-23 08:28:14.272951
54421718     USD 650      USD 2024-09-24 12:26:30.907747
54421718     USD 650      USD 2024-09-29 23:47:13.054893
54421718   $ 630.000        $ 2025-03-09 00:26:57.589025
54423448   USD 1.900      USD 2024-09-23 08:28:14.272951
54423448   USD 1.900      USD 2024-09-24 12:26:30.907747
54423448   USD 1.900      USD 2024-09-29 23:47:13.054893
54423448 $ 2.500.000        $ 2025-03-09 00:26:57.589025
54433576     USD 550      USD 2024-09-23 08:28:14.272951
54433576   $ 550.000        $ 2024-09-24 12:26:30.907747
54433576   $ 650.000        $ 2024-09-29 23:47:13.054893
54439055     USD 730      USD 2024-09-23 08:28:14.272951
54439055   $ 860.000        $ 2024-09-24 12:26:30.907747
54439055   $ 860.000        $ 2024-09-29 23:47:13.054893
54464964     USD 460      USD 2024-09-23 08:28:14.272951
54464964     USD 460      USD 2024-09-24 12:26:30.907747
54464964     USD 460      USD 2024-09-29 23:47:13.054893
54464964   $ 480.000        $ 2025-03-09 00:26:57.589025
54466731     USD 700      USD 2024-09-23 08:28:14.272951
54466731     USD 700      USD 2024-09-24 12:26:30.907747
54466731   $ 700.000        $ 2024-09-29 23:47:13.054893
54469665 USD 650.000      USD 2024-09-23 08:28:14.272951
54469665 USD 650.000      USD 2024-09-24 12:26:30.907747
54469665   $ 650.000        $ 2024-09-29 23:47:13.054893
54473025 $ 1.200.000        $ 2024-09-23 08:28:14.272951
54473025     USD 800      USD 2024-09-24 12:26:30.907747
54473025     USD 800      USD 2024-09-29 23:47:13.054893
54477151     USD 950      USD 2024-09-23 08:28:14.272951
54477151     USD 950      USD 2024-09-24 12:26:30.907747
54477151     USD 950      USD 2024-09-29 23:47:13.054893
54477151   $ 900.000        $ 2025-03-09 00:26:57.589025
54487448     USD 730      USD 2024-09-23 08:28:14.272951
54487448   $ 860.000        $ 2024-09-24 12:26:30.907747
54487448   $ 860.000        $ 2024-09-29 23:47:13.054893
54495149 $ 1.800.000        $ 2024-09-23 08:28:14.272951
54495149 $ 1.800.000        $ 2024-09-24 12:26:30.907747
54495149 $ 1.800.000        $ 2024-09-29 23:47:13.054893
54495149   USD 1.500      USD 2025-03-09 00:26:57.589025
54497341     USD 400      USD 2024-09-23 08:28:14.272951
54497341     USD 400      USD 2024-09-24 12:26:30.907747
54497341     USD 400      USD 2024-09-29 23:47:13.054893
54497341   $ 450.000        $ 2025-03-09 00:26:57.589025
54497845     USD 400      USD 2024-09-23 08:28:14.272951
54497845     USD 400      USD 2024-09-24 12:26:30.907747
54497845   $ 500.000        $ 2024-09-29 23:47:13.054893
54500309   USD 1.400      USD 2024-09-23 08:28:14.272951
54500309   USD 1.400      USD 2024-09-24 12:26:30.907747
54500309   USD 1.400      USD 2024-09-29 23:47:13.054893
54500309     $ 1.850        $ 2025-03-09 00:26:57.589025
54503391     USD 700      USD 2024-09-23 08:28:14.272951
54503391     USD 700      USD 2024-09-24 12:26:30.907747
54503391   $ 700.000        $ 2024-09-29 23:47:13.054893
54503799     USD 400      USD 2024-09-23 08:28:14.272951
54503799     USD 400      USD 2024-09-24 12:26:30.907747
54503799   $ 500.000        $ 2024-09-29 23:47:13.054893
54504319     USD 700      USD 2024-09-23 08:28:14.272951
54504319     USD 700      USD 2024-09-24 12:26:30.907747
54504319   $ 699.000        $ 2024-09-29 23:47:13.054893
54510385     USD 550      USD 2024-09-23 08:28:14.272951
54510385     USD 550      USD 2024-09-24 12:26:30.907747
54510385   $ 550.000        $ 2024-09-29 23:47:13.054893
54510524     USD 700      USD 2024-09-23 08:28:14.272951
54510524     USD 700      USD 2024-09-24 12:26:30.907747
54510524   $ 700.000        $ 2024-09-29 23:47:13.054893
54519867     USD 600      USD 2024-09-23 08:28:14.272951
54519867   $ 600.000        $ 2024-09-24 12:26:30.907747
54519867   $ 600.000        $ 2024-09-29 23:47:13.054893
54525332     USD 600      USD 2024-09-24 12:26:30.907747
54525332   $ 570.000        $ 2024-09-29 23:47:13.054893
54542402   $ 550.000        $ 2024-09-23 08:28:14.272951
54542402   $ 550.000        $ 2024-09-24 12:26:30.907747
54542402   $ 550.000        $ 2024-09-29 23:47:13.054893
54542402     USD 530      USD 2025-03-09 00:26:57.589025
54547951     USD 850      USD 2024-09-23 08:28:14.272951
54547951     USD 850      USD 2024-09-24 12:26:30.907747
54547951     USD 850      USD 2024-09-29 23:47:13.054893
54547951 $ 1.100.000        $ 2025-03-09 00:26:57.589025
54553259     USD 400      USD 2024-09-23 08:28:14.272951
54553259     USD 400      USD 2024-09-24 12:26:30.907747
54553259   $ 450.000        $ 2024-09-29 23:47:13.054893
54553638   $ 500.000        $ 2024-09-23 08:28:14.272951
54553638   $ 500.000        $ 2024-09-24 12:26:30.907747
54553638     USD 500      USD 2024-09-29 23:47:13.054893
54556183   $ 750.000        $ 2024-09-24 12:26:30.907747
54556183     USD 750      USD 2024-09-29 23:47:13.054893
54559566     USD 300      USD 2024-09-24 12:26:30.907747
54559566   $ 320.000        $ 2024-09-29 23:47:13.054893

## Verificación de duplicados exactos

Se verifica si existen registros completamente idénticos en todas sus columnas.

Los registros de una misma propiedad en diferentes fechas no se consideran duplicados exactos, ya que pueden representar distintas versiones de una misma publicación.

La conversión temporal a texto permite realizar la comparación incluso cuando existen columnas que contienen listas.

In [62]:
# Convierte temporalmente las columnas a texto y cuenta registros 
# completamente idénticos.

duplicados_exactos = df_clean.astype(str).duplicated().sum()

print(
    "Duplicados exactos:",
    duplicados_exactos
)

Duplicados exactos: 0

### Resultado

No se encontraron registros completamente duplicados en el dataset.

Aunque existen propiedades con el mismo `id` en diferentes fechas de scraping, estos registros no son duplicados exactos y pueden contener cambios en precio, moneda u otra información relevante.