# Exploración inicial del dataset

## Objetivo

En este notebook se realiza una primera exploración del dataset de alquileres de departamentos en CABA.

El objetivo es comprender la estructura de los datos, identificar las variables disponibles y detectar posibles problemas antes de comenzar la etapa de limpieza y transformación.

In [2]:
import pandas as pd

df = pd.read_pickle("../data/raw/alquiler_departamentos_consolidado.pkl")

In [3]:
df.head()

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
0,54517317,USD 500,"Belgrano, Capital Federal",Blanco Encalada al 1401,"[58 m² tot., 1 amb., 1 baño]",Monoambiente con Jardin con Parrilla Privado y...,$ 235.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
1,54209811,USD 950,"Palermo Hollywood, Palermo",Convención al 1900,"[55 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Palermo departamento en alquiler totalmente eq...,$ 230.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
2,54139823,$ 470.000,"Núñez, Capital Federal",Av. Libertador y Manzanares 1600,"[38 m² tot., 1 amb., 1 baño]",Monoambiente en alquiler en nuñez. Excelente u...,$ 80.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
3,54339837,$ 320.000,"Caballito, Capital Federal",ARANGUREN 600. Entre Colpayo y Avenida pueyrredon,"[30 m² tot., 1 amb., 1 dorm.]",Alquiler de Departamento 1 ambiente en Caballi...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
4,54239549,USD 1.100,"Belgrano, Capital Federal",Virrey Loreto 2200,"[75 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Moderno Departamento 2 ambientes. Muy luminoso...,$ 200.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler

In [5]:
df.shape

(57343, 11)

In [6]:
df.columns

Index(['id', 'Price', 'Location', 'Address', 'Features', 'Description',
       'Expensas', 'Link', 'scrap_date', 'type_building', 'type_operation'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57343 entries, 0 to 57342
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              57343 non-null  object
 1   Price           57343 non-null  object
 2   Location        57343 non-null  object
 3   Address         57343 non-null  object
 4   Features        57343 non-null  object
 5   Description     57343 non-null  object
 6   Expensas        45375 non-null  object
 7   Link            57343 non-null  object
 8   scrap_date      57343 non-null  datetime64[us]
 9   type_building   57343 non-null  object
 10  type_operation  57343 non-null  object
dtypes: datetime64[us](1), object(10)
memory usage: 4.8+ MB

In [9]:
df.head(10)

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
0,54517317,USD 500,"Belgrano, Capital Federal",Blanco Encalada al 1401,"[58 m² tot., 1 amb., 1 baño]",Monoambiente con Jardin con Parrilla Privado y...,$ 235.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
1,54209811,USD 950,"Palermo Hollywood, Palermo",Convención al 1900,"[55 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Palermo departamento en alquiler totalmente eq...,$ 230.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
2,54139823,$ 470.000,"Núñez, Capital Federal",Av. Libertador y Manzanares 1600,"[38 m² tot., 1 amb., 1 baño]",Monoambiente en alquiler en nuñez. Excelente u...,$ 80.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
3,54339837,$ 320.000,"Caballito, Capital Federal",ARANGUREN 600. Entre Colpayo y Avenida pueyrredon,"[30 m² tot., 1 amb., 1 dorm.]",Alquiler de Departamento 1 ambiente en Caballi...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
4,54239549,USD 1.100,"Belgrano, Capital Federal",Virrey Loreto 2200,"[75 m² tot., 2 amb., 1 dorm., 1 baño, 1 coch.]",Moderno Departamento 2 ambientes. Muy luminoso...,$ 200.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
5,54373994,$ 650.000,"Palermo, Capital Federal","SCALABRINI ORTIZ, RAUL, AV. 2700. Entre Beruti...","[70 m² tot., 4 amb., 3 dorm., 2 baños]","Departamento 4 ambientes en Palermo, Capital F...",$ 190.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
6,54437016,$ 900.000,"Palermo, Capital Federal",Mansilla 3700,"[65 m² tot., 3 amb., 2 dorm., 1 baño]",Ubicación: Apartamento de tres ambientes en un...,$ 83.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
7,54549118,$ 590.000,"Palermo, Capital Federal",Uriarte 2300,"[33 m² tot., 1 amb., 1 baño]",Corredor Responsable: Monica Alejandra Mazza c...,$ 121.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
8,52914698,USD 1.300,"Villa Crespo, Capital Federal",Costa Rica al 4300,"[66 m² tot., 3 amb., 2 dorm., 1 baño, 1 coch.]",Tres ambientes con balcón ubicado en costa ric...,$ 80.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
9,54449591,$ 450.000,"Colegiales, Capital Federal",Conde al 700,"[43 m² tot., 2 amb., 1 dorm., 1 baño]","Departamento 2 ambientes, excelente ubicaciónD...",$ 95.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler

In [10]:
df.isnull().sum()

id                    0
Price                 0
Location              0
Address               0
Features              0
Description           0
Expensas          11968
Link                  0
scrap_date            0
type_building         0
type_operation        0
dtype: int64

## Observaciones

- El dataset contiene 57.343 publicaciones.
- La columna `Expensas` presenta 11.968 valores faltantes.
- El resto de las columnas no presenta valores nulos.
- Será necesario analizar más adelante cómo tratar los valores faltantes de `Expensas`.

In [11]:
df["scrap_date"].nunique()

5

In [12]:
df["scrap_date"].sort_values().unique()

<DatetimeArray>
['2024-09-23 08:28:14.272951', '2024-09-24 12:26:30.907747',
 '2024-09-29 23:47:13.054893', '2025-03-09 00:26:57.589025',
 '2025-07-12 13:35:44.207335']
Length: 5, dtype: datetime64[us]

## Observaciones sobre la fecha de scraping

- El dataset contiene publicaciones obtenidas en 5 fechas distintas.
- Las fechas abarcan desde septiembre de 2024 hasta julio de 2025.
- Esto permitirá realizar análisis temporales una vez que los datos estén limpios.

In [13]:
df.describe(include="all")

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
count,57343,57343,57343,57343,57343,57343,45375,57343,57343,57343,57343
unique,31338,736,89,23235,4039,31655,2483,31748,NaN,1,1
top,54487465,$ 450.000,"Palermo, Capital Federal",Dirección no informada,"[40 m² tot., 2 amb., 1 dorm., 1 baño]",Edificio en torreSeguridad 24 hrsParque / Jard...,$ 100.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,NaN,departamentos,alquiler
freq,5,2613,6614,430,1576,31,1825,5,NaN,57343,57343
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-15 04:01:33.844427,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-23 08:28:14.272951,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-24 12:26:30.907747,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-29 23:47:13.054893,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-09 00:26:57.589025,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-12 13:35:44.207335,NaN,NaN

In [14]:
df["id"].value_counts().head(10)

id
54487465    5
53760505    5
52978480    5
44626608    5
48296864    5
45818662    5
54133703    5
52969886    5
54239592    5
53263870    5
Name: count, dtype: int64

In [15]:
df[df["id"] == "54487465"]

,id,Price,Location,Address,Features,Description,Expensas,Link,scrap_date,type_building,type_operation
34,54487465,$ 380.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 65.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-23 08:28:14.272951,departamentos,alquiler
14824,54487465,$ 380.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 65.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-24 12:26:30.907747,departamentos,alquiler
28126,54487465,$ 380.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 65.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2024-09-29 23:47:13.054893,departamentos,alquiler
42499,54487465,$ 400.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2025-03-09 00:26:57.589025,departamentos,alquiler
55587,54487465,$ 440.000,"La Paternal, Capital Federal",Av. San Martín 3420 - Caba.,"[35 m² tot., 1 amb., 1 dorm., 1 baño]",Monoambiente A Estrenar. Inmejorable ubicación...,$ 70.000 Expensas,https://www.zonaprop.com.ar/propiedades/clasif...,2025-07-12 13:35:44.207335,departamentos,alquiler

## Observaciones sobre los identificadores (`id`)

- Los identificadores no representan registros únicos del dataset.
- Un mismo `id` puede aparecer en distintas fechas de scraping.
- Esto indica que el dataset conserva el historial de una misma publicación a lo largo del tiempo.
- Gracias a esta característica será posible realizar análisis de evolución de precios y expensas entre distintas fechas.

In [16]:
df["type_operation"].value_counts()

type_operation
alquiler    57343
Name: count, dtype: int64

In [17]:
df["type_building"].value_counts()

type_building
departamentos    57343
Name: count, dtype: int64

## Observaciones sobre variables constantes

- La columna `type_operation` contiene únicamente el valor `alquiler`.
- La columna `type_building` contiene únicamente el valor `departamentos`.
- Ambas columnas no aportan variabilidad al análisis y podrían eliminarse durante la etapa de limpieza de datos.

In [18]:
df["Location"].value_counts()

Location
Palermo, Capital Federal            6614
Recoleta, Capital Federal           6503
Belgrano, Capital Federal           4525
Puerto Madero, Capital Federal      3276
Barrio Norte, Capital Federal       2636
                                    ...
Belgrano C, Colegiales                 2
Botánico, Recoleta                     1
Villa Riachuelo, Capital Federal       1
Temperley, San Telmo                   1
Los Perales, Mataderos                 1
Name: count, Length: 89, dtype: int64